{
    "ID": {
        "GitHub_Advisory_Database": {
            "aliases": [
                "CVE-2019-6446"
            ]
        },
        "Nomisec": {
            "id": 186728497,
            "name": "CVE-2019-6446",
            "full_name": "RayScri/CVE-2019-6446"
        }
    },
    "summary": "Numpy Deserialization of Untrusted Data",
    "details": {
        "GitHub_Advisory_Database": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
    },
    "description": {
        "Nomisec": "Numpy deserialization command execution"
    },
    "topics": [
        "object",
        "python",
        "trusted",
        "load",
        "issue",
        "applications",
        "deserialization",
        "uses",
        "demonstrated",
        "example"
    ],
    "severity": [],
    "affected": [],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
        },
        {
            "type": "WEB",
            "url": "https://github.com/numpy/numpy/issues/12759"
        },
        {
            "type": "WEB",
            "url": "https://github.com/numpy/numpy/pull/12889"
        },
        {
            "type": "WEB",
            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
        },
        {
            "type": "WEB",
            "url": "https://access.redhat.com/errata/RHSA-2019:3704"
        },
        {
            "type": "WEB",
            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
        },
        {
            "type": "PACKAGE",
            "url": "https://github.com/numpy/numpy"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
        },
        {
            "type": "WEB",
            "url": "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
        },
        {
            "type": "WEB",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
        },
        {
            "type": "WEB",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
        },
        {
            "type": "WEB",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
        },
        {
            "type": "WEB",
            "url": "http://www.securityfocus.com/bid/106670"
        }
    ],
    "proof_of_concept": {
        "owner": {
            "html_url": "https://github.com/RayScri"
        },
        "html_url": "https://github.com/RayScri/CVE-2019-6446"
    },
    "has_discussions": null,
    "database_specific": {
        "cwe_ids": [
            "CWE-502"
        ],
        "severity": "CRITICAL",
        "github_reviewed": true,
        "github_reviewed_at": "2023-07-18T20:19:35Z",
        "nvd_published_at": "2019-01-16T05:29:01Z"
    },
    "Time_Description": {
        "GitHub_Advisory_Database": {
            "modified": "2024-04-22T21:20:55Z",
            "published": "2022-05-24T22:00:57Z",
            "withdrawn": null
        },
        "Nomisec": {
            "created_at": "2019-05-15T01:39:53Z",
            "updated_at": "2024-08-12T19:48:53Z",
            "pushed_at": "2019-05-15T02:22:29Z"
        }
    }
}