{
    "ID": {
        "GitHub_Advisory_Database": {
            "aliases": [
                "CVE-2020-28948"
            ]
        },
        "Nomisec1": {
            "id": 316481683,
            "name": "CVE-2020-28948-and-CVE-2020-28949",
            "full_name": "0x240x23elu/CVE-2020-28948-and-CVE-2020-28949"
        },
        "Nomisec2": {
            "id": 370402145,
            "name": "cve-2020-28948",
            "full_name": "nopdata/cve-2020-28948"
        },
        "Nomisec3": {
            "id": 544836274,
            "name": "PoC-for-CVE-2020-28948-CVE-2020-28949",
            "full_name": "JinHao-L/PoC-for-CVE-2020-28948-CVE-2020-28949"
        }
    },
    "summary": "Deserialization of Untrusted Data in Archive_Tar",
    "details": {
        "GitHub_Advisory_Database": "Archive_Tar through 1.4.10 allows an unserialization attack because `phar:` is blocked but `PHAR:` is not blocked. See: https://github.com/pear/Archive_Tar/issues/33"
    },
    "description": {
        "Nomisec1": null,
        "Nomisec2": null,
        "Nomisec3": null
    },
    "topics": [
        "issues",
        "github",
        "com",
        "https",
        "attack",
        "10",
        "allows",
        "escape",
        "escalation",
        "escalate"
    ],
    "severity": [],
    "affected": [],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28948"
        },
        {
            "type": "WEB",
            "url": "https://github.com/pear/Archive_Tar/issues/33"
        },
        {
            "type": "WEB",
            "url": "https://github.com/pear/Archive_Tar/commit/0670a05fdab997036a3fc3ef113b8f5922e574da"
        },
        {
            "type": "PACKAGE",
            "url": "https://github.com/pear/Archive_Tar"
        },
        {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00045.html"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/42GPGVVFTLJYAKRI75IVB5R45NYQGEUR"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4V35LBRM6HBCXBVCITKQ4UEBTXO2EG7B"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5KSFM672XW3X6BR7TVKRD63SLZGKK437"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KWM4CTMEGAC4I2CHYNJVSROY4CVXVEUT"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NBYZSHYTIOBK6V7C4N7TP6KIKCRKLVWP"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VJQQYDAOWHD6RDITDRPHFW7WY6BS3V5N"
        },
        {
            "type": "WEB",
            "url": "https://security.gentoo.org/glsa/202101-23"
        },
        {
            "type": "WEB",
            "url": "https://www.debian.org/security/2020/dsa-4817"
        },
        {
            "type": "WEB",
            "url": "https://www.drupal.org/sa-core-2020-013"
        }
    ],
    "proof_of_concept": {
        "owner1": {
            "html_url": "https://github.com/0x240x23elu"
        },
        "html_url1": "https://github.com/0x240x23elu/CVE-2020-28948-and-CVE-2020-28949",
        "owner2": {
            "html_url": "https://github.com/nopdata"
        },
        "html_url2": "https://github.com/nopdata/cve-2020-28948",
        "owner3": {
            "html_url": "https://github.com/JinHao-L"
        },
        "html_url3": "https://github.com/JinHao-L/PoC-for-CVE-2020-28948-CVE-2020-28949"
    },
    "has_discussions": null,
    "database_specific": {
        "cwe_ids": [
            "CWE-502"
        ],
        "severity": "HIGH",
        "github_reviewed": true,
        "github_reviewed_at": "2021-03-23T00:18:26Z",
        "nvd_published_at": "2020-11-19T19:15:00Z"
    },
    "Time_Description": {
        "GitHub_Advisory_Database": {
            "modified": "2023-07-05T23:21:42Z",
            "published": "2021-04-22T16:20:50Z",
            "withdrawn": null
        },
        "Nomisec": {
            "created_at1": "2020-11-27T11:21:46Z",
            "updated_at1": "2024-08-12T20:07:59Z",
            "pushed_at1": "2020-11-27T11:26:01Z",
            "created_at2": "2021-05-24T15:36:16Z",
            "updated_at2": "2021-05-24T15:39:06Z",
            "pushed_at2": "2021-05-24T15:39:03Z",
            "created_at3": "2022-10-03T10:10:11Z",
            "updated_at3": "2022-10-03T10:19:11Z",
            "pushed_at3": "2022-10-17T13:56:39Z"
        }
    }
}