{
    "ID": {
        "GitHub_Advisory_Database": {
            "aliases": [
                "CVE-2022-34265"
            ]
        },
        "Nomisec1": {
            "id": 511432180,
            "name": "CVE-2022-34265",
            "full_name": "aeyesec/CVE-2022-34265"
        },
        "Nomisec2": {
            "id": 513523694,
            "name": "CVE-2022-34265",
            "full_name": "traumatising/CVE-2022-34265"
        },
        "Nomisec3": {
            "id": 528313090,
            "name": "CVE-2022-34265",
            "full_name": "ZhaoQi99/CVE-2022-34265"
        },
        "Nomisec4": {
            "id": 534397698,
            "name": "CTF_Django_CVE-2022-34265",
            "full_name": "lnwza0x0a/CTF_Django_CVE-2022-34265"
        }
    },
    "summary": "Django `Trunc()` and `Extract()` database functions vulnerable to SQL Injection",
    "details": {
        "GitHub_Advisory_Database": "An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The `Trunc()` and `Extract()` database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected."
    },
    "description": {
        "Nomisec1": "PoC for CVE-2022-34265 (Django)",
        "Nomisec2": "CVE-2022-34265 Vulnerability ",
        "Nomisec3": "PoC for CVE-2022-34265",
        "Nomisec4": null
    },
    "topics": [
        "2022",
        "extract",
        "known",
        "poc",
        "applications",
        "functions",
        "list",
        "untrusted",
        "value",
        "database"
    ],
    "severity": [],
    "affected": [],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-34265"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/0dc9c016fadb71a067e5a42be30164e3f96c0492"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/5e2f4ddf2940704a26a4ac782b851989668d74db"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/877c800f255ccaa7abde1fb944de45d1616f5cc9"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/a9010fe5555e6086a9d9ae50069579400ef0685e"
        },
        {
            "type": "WEB",
            "url": "https://docs.djangoproject.com/en/4.0/releases/security"
        },
        {
            "type": "ADVISORY",
            "url": "https://github.com/advisories/GHSA-p64x-8rxx-wf6q"
        },
        {
            "type": "PACKAGE",
            "url": "https://github.com/django/django"
        },
        {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-213.yaml"
        },
        {
            "type": "WEB",
            "url": "https://groups.google.com/forum/#!forum/django-announce"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI"
        },
        {
            "type": "WEB",
            "url": "https://security.netapp.com/advisory/ntap-20220818-0006"
        },
        {
            "type": "WEB",
            "url": "https://www.debian.org/security/2022/dsa-5254"
        },
        {
            "type": "WEB",
            "url": "https://www.djangoproject.com/weblog/2022/jul/04/security-releases"
        }
    ],
    "proof_of_concept": {
        "owner1": {
            "html_url": "https://github.com/aeyesec"
        },
        "html_url1": "https://github.com/aeyesec/CVE-2022-34265",
        "owner2": {
            "html_url": "https://github.com/traumatising"
        },
        "html_url2": "https://github.com/traumatising/CVE-2022-34265",
        "owner3": {
            "html_url": "https://github.com/ZhaoQi99"
        },
        "html_url3": "https://github.com/ZhaoQi99/CVE-2022-34265",
        "owner4": {
            "html_url": "https://github.com/lnwza0x0a"
        },
        "html_url4": "https://github.com/lnwza0x0a/CTF_Django_CVE-2022-34265"
    },
    "has_discussions": null,
    "database_specific": {
        "cwe_ids": [
            "CWE-89"
        ],
        "severity": "CRITICAL",
        "github_reviewed": true,
        "github_reviewed_at": "2022-07-05T21:08:03Z",
        "nvd_published_at": "2022-07-04T16:15:00Z"
    },
    "Time_Description": {
        "GitHub_Advisory_Database": {
            "modified": "2022-08-19T17:09:36Z",
            "published": "2022-07-05T00:00:53Z",
            "withdrawn": null
        },
        "Nomisec": {
            "created_at1": "2022-07-07T07:45:28Z",
            "updated_at1": "2024-08-12T20:24:48Z",
            "pushed_at1": "2022-07-30T07:53:43Z",
            "created_at2": "2022-07-13T13:02:41Z",
            "updated_at2": "2022-07-17T10:07:36Z",
            "pushed_at2": "2022-07-13T13:07:01Z",
            "created_at3": "2022-08-24T07:29:30Z",
            "updated_at3": "2023-02-14T21:32:51Z",
            "pushed_at3": "2022-08-26T03:28:01Z",
            "created_at4": "2022-09-08T21:22:28Z",
            "updated_at4": "2022-10-07T11:01:14Z",
            "pushed_at4": "2022-09-08T22:10:47Z"
        }
    }
}